### ISSUE TITLE
What's the variable 'filter_ones' used for in the source code (CoL_layer.py).

### ISSUE THREAD

**Issue by IvanFei** [Shevlev/Co-occurrence-Neural-Network#1]
Hello @Shevlev,
 
Congratulations on your paper being accepted by CVPR 2019. 

I encountered a problem while reading the source code.

The `filter_ones` would make the `mask_temp` blur, which is not consistent with the paper. The paper just calculate the box which has the black center in bin `i=0`. (details as figure shown)

best wishes.

![image](https://user-images.githubusercontent.com/24504559/70607943-489ab200-1c3a-11ea-9096-6d37e0db5a60.png)

**Comment by Shevlev** [comment]
Hello,

Thank you.
You asked a very good question.

[image: image.png]
defines the one-cell filter with the shape [1, 1, 1, 1, 1]
as you also can see in the definition:
[image: image.png]
so it doesn't do any blurring to the temp_mask.

filter_ones is defined in such a way in order to use Convolution in the
calculation and improve performance.
it just helps to fetch the relevant value from temp_mask.

Don't hesitate to ask any questions that you have.
Regards,
Ira.

**Comment by IvanFei** [comment]
Hello @Shevlev ,
Thank you for your kind reply.

It seems that the images you provided cannot be displayed properly. 
Could you please re-post the images in your reply.
Thank you.

Best wishes.

**Comment by Shevlev** [comment]
Hello,

Thank you.
You asked a very good question.
filter_ones = tf.ones([1, 1, 1, 1, 1])
defines the one-cell filter with the shape [1, 1, 1, 1, 1]
as you also can see in the definition from the Tensorflow website:
tf.ones(
       shape,
       dtype=tf.dtype.float32,
       name = None
)
so it doesn't do any blurring to the temp_mask.

filter_ones is defined in such a way in order to use Convolution in the
calculation and improve performance.
it just helps to fetch the relevant value from temp_mask.

Don't hesitate to ask any questions that you have.
Regards,

**Comment by IvanFei** [comment]
@Shevlev, Thank you for your kind reply.
I have understood the role of `filter_ones` .

However, Here is another question. It is about the output (`total_conv`) of `CoNN_layer` function.

The shape of `total_conv` is [sp0, sp1/stride, sp1/stride, sp3]. 
It only can deal with the square matrix? 

It seems that [sp0, sp1/stride, sp2/stride, sp3] is more reasonable. 

Best wishes.

**Comment by Shevlev** [comment]
Hello,

I don't understand your question.
the deep co-occurrence matrix has to be square matrix because it learns the
best parameter between each two values in the input.
the option of stride added only in case you want to learn and apply learned
co-occurrence matrix not on each pixel but with stride.

Regards,
Ira.

**Comment by IvanFei** [comment]
Hello,

I am sorry that my expression was not clear enough.

The shape of `total_conv` is [sp0, `sp1/stride`, `sp1/stride`, sp3], which is square matrix (Not consider about the batch size and channel). 

However, when the features map (`layer_input`) is not square matrix, this would cause a bug (due to `total_conv = total_conv + temp_result`). 

For example: 
                       when the shape of `layer_input`  is [1, 5, 10, 1]. `strides=1`
                       the shape of `total_conv` will be [1, 5, 5, 1]
                       but the shape of `temp_result` is [1, 5, 10, 1]
                       Thus, `total_conv = total_conv + temp_result` would be error.

Best wishes.

**Comment by Shevlev** [comment]
hello,

Thank you for explanation.
you are right I missed deviation of the sp2 = int(sp2 / strides)

Thanks, Ira.

**Comment by IvanFei** [comment]
Hello, 

Thank you for your kind reply to my question.

The repo below is my pytorch implementation of Co-Occurrence Neural Network.

https://github.com/IvanFei/Co-Occurrence-Layer.pytorch 

Thank you, 
IvanFei
